config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'

resources "contacts", only: [:new, :create]
  resources :prices

  devise_for :users
  root 'home#index'


  resources :posts do
    resources :comments
  end


  resources :demos

  resources :projects

  get 'pages/our_thing'

  get 'pages/blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  append :remote_ip, :user_agent, :session

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "webelfs",
      :to => "compilitrate@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/demo.rb
class Demo < ApplicationRecord
  dragonfly_accessor :dpic
  dragonfly_accessor :mpic
  dragonfly_accessor :tpic
  dragonfly_accessor :r1pic
  dragonfly_accessor :r2pic
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  dragonfly_accessor :pic1
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :verify_is_admin, :only => [:new, :edit, :create, :destroy]
  def new
    @demo = Demo.new
  end

  def create
    @demo = Demo.new(demo_params)
    if @demo.save
      redirect_to @demo
    else
      render 'new'
    end
  end

  def index
    @demos = Demo.all.order('created_at DESC')
  end

  def show
    @demo = Demo.find(params[:id])
  end

  def edit
    @demo = Demo.find(params[:id])
  end

  def update
    @demo = Demo.find(params[:id])
    if @demo.update(params[:demo].permit(:d_pic, :m_pic, :t_pic, :r1_pic, :r2_pic, :name, :b_amount, :description))
      redirect_to demo_path
    else
      render 'edit'
    end
  end

  def destroy
    @demo = Demo.find(params[:id])
    @demo.destroy
    redirect_to demos_path
  end

  private

  def demo_params
    params.require(:demo).permit(:dpic, :mpic, :tpic, :r1pic, :r2pic, :name, :b_amount, :description)
  end

  def verify_is_admin
  (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def our_thing
  end
  def blog
  end
end

app/controllers/posts_controller.rb
# takes care of posts
class PostsController < ApplicationController
  before_action :verify_is_admin, :only => [:new, :edit, :create, :destroy]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to post_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def verify_is_admin
  (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end

end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :verify_is_admin, :only => [:new, :edit, :create, :destroy]
  def new
    @price = Price.new
  end

  def create
    @price = Price.new(price_params)
    if @price.save
      redirect_to @price
    else
      render 'new'
    end
  end

  def index
    @prices = Price.all.order('created_at DESC')
  end

  def show
    @price = Price.find(params[:id])
  end

  def edit
    @price = Price.find(params[:id])
  end

  def update
    @price = Price.find(params[:id])
    if @price.update(params[:price].permit(:b_amount, :name, :description, :indepth, :features))
      redirect_to price_path
    else
      render 'edit'
    end
  end

  def destroy
    @price = Price.find(params[:id])
    @price.destroy
    redirect_to prices_path
  end


  private

  def price_params
    params.require(:price).permit(:b_amount, :name, :description, :indepth, :features)
  end

  def verify_is_admin
  (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.erb
<div class= 'comment clearfix'>
  <div class='comment_content'>
    <p class='comment_name'><strong><%= comment.name %></strong></p>
    <p class='comment_body'><%= comment.body %></p>
    <p class='comment_time'><%= time_ago_in_words(comment.created_at) %> Ago </p>
  </div>

  <p>
    <%= button_to 'delete', [comment.post, comment], method: :delete, class: 'button',
    data: { confirm: 'Are you sure?'} %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f|%>
<p>
  <%= f.label :name %></br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :body %></br>
  <%= f.text_area :body %>
</p>
</br>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/demos/edit.html.erb
<%= form_for @demo do |f| %>
<p><%= f.label :d_pic %></br>
   <%= image_tag @demo.dpic.thumb('400x200#').url if @demo.dpic_stored? %>
</p>
<p><%= f.label :m_pic %></br>
   <%= image_tag @demo.mpic.thumb('400x200#').url if @demo.mpic_stored? %>
</p>
<p><%= f.label :t_pic %></br>
   <%= image_tag @demo.tpic.thumb('400x200#').url if @demo.tpic_stored? %>
</p>
<p><%= f.label :r1_pic %></br>
   <%= image_tag @demo.r1pic.thumb('400x200#').url if @demo.r1pic_stored? %>
</p>
<p><%= f.label :r2_pic %></br>
   <%= image_tag @demo.r2pic.thumb('400x200#').url if @demo.r2pic_stored? %>
</p>
<p><%= f.label :name %></br>
   <%= f.text_field :name %>
</p>
<p><%= f.label :b_amount %></br>
   <%= f.text_field :b_amount %>
</p>
<p><%= f.label :description %></br>
   <%= f.text_field :description %>
</p>
<p><%= f.submit %>
</p>
<% end %>
<%= button_to 'Delete', @demo, method: :delete, data: {confirm: 'are you sure?'}%>

app/views/demos/index.html.erb
<div class="row">
  <h3 align='center'>viewing a list of existing demos</h3>
  <div class="col-md-1">

    <div class="contain">
    <%= image_tag("rails.png", class: "img-responsive") %>

    <%= image_tag("reb.png", class: "img-responsive") %>
    </div>



  </div>
  <div class="col-md-10">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading panel-heading-custom" role="tab" id="headingFive">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                Samples.
            </a>
          </h4>
        </div>
        <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
          <div class="panel-body">
            <p>Here we present what is ready (and functional); ready to be cloned your way</p>
          </div>
        </div>
      </div>


    </div>
    <% @demos.each do |demo| %>
    <div class="demo">

  <%= link_to demo.name, demo_path(demo) %><br>
  <%= link_to demo_path(demo) do %>

    <%= image_tag (demo.tpic.thumb('244x137#')).url %>
    <% end %>
  <br>
   <p style="text-align:right" > <%= demo.description %> </p>
  <br>
  <p style="text-align:left" > <%= demo.b_amount %>_$ </p>
    </div>
    <hr><br>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading panel-heading-custom" role="tab" id="headingTwo">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Open Requests
          </a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
          <p>Get your idea made from scratch;<a href="https://webelfs.com/contacts/new"> contact_us_here</a></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-1">
<a href="https://www.facebook.com/elfonweb/"><i class="fa fa-facebook"></i></a> |<%= link_to contacts_new_path do %> <i class="fa fa-envelope"></i><% end %>
  </div>
</div>

app/views/demos/new.html.erb
<%= form_for @demo do |f| %>
<p><%= f.label :desktoppic %></br>
   <%= f.file_field :dpic %>
</p>
<p><%= f.label :mobilepic %></br>
   <%= f.file_field :mpic %>
</p>
<p><%= f.label :mobilelandscapepic %></br>
   <%= f.file_field :tpic %>
</p>
<p><%= f.label :tabletpic %></br>
   <%= f.file_field :r1pic %>
</p>
<p><%= f.label :tabletlandscapepic %></br>
   <%= f.file_field :r2pic %>
</p>
<p><%= f.label :name %></br>
   <%= f.text_field :name %>
</p>
<p><%= f.label :b_amount %></br>
   <%= f.text_field :b_amount %>
</p>
<p><%= f.label :description %></br>
   <%= f.text_field :description %>
</p>
<p><%= f.submit :value => "create demo", :class => 'btn' %>
</p>
<% end %>

app/views/demos/show.html.erb
<div class="row">
  <div class="col-md-1">
      <div class="contain">
    <%= image_tag("rails.png", class: "img-responsive") %>
    <%= image_tag("reb.png", class: "img-responsive") %>
  </div>
  </div>
  <div class="col-md-10">
<h1>Demos</h1>
<hr>
<div class="disp" style="float:left">
desktop_view<br>
<%= image_tag @demo.dpic.thumb('480x300#').url if @demo.dpic_stored? %>
</div>
<div class="disp" >
mobile_view<br>
<%= image_tag @demo.mpic.thumb('137x244#').url if @demo.mpic_stored? %>
</div>
<div class="disp" >
mobile landscape_view<br>
<%= image_tag @demo.tpic.thumb('244x137#').url if @demo.tpic_stored? %>
</div>
<div  class="disp" style="float:left">
tablet/i-pad_view<br>
<%= image_tag @demo.r1pic.thumb('256x341#').url if @demo.r1pic_stored? %>
</div>
<div class="disp" >
landscaped tablet/i-pad_view<br>
<%= image_tag @demo.r2pic.thumb('341x256#').url if @demo.r2pic_stored? %>
</div>

<br><br><br><br>

<hr>
<h2 style="text-align: center">Description</h2>
<table>
  <tr><th>Name:</th> <td><%= @demo.name %></td></tr>
  <tr><th>Base_cost:</th> <td><%= @demo.b_amount %>_$</td></tr>
  <tr><th>Use:</th> <td><%= @demo.description %></td></tr>

</table><br><br>
<div class="back">
<%= link_to 'Back', :back %>
</div>
</div>
<div class="col-md-1">
<a href="https://www.facebook.com/elfonweb/"><i class="fa fa-facebook"></i></a> |<%= link_to contacts_new_path do %> <i class="fa fa-envelope"></i><% end %>

</div>
</div>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
  <%= form_for @post do |f| %>
    <p><%= f.label :title %></br>
       <%= f.text_field :title %>
    </p>
    <p><%= f.label :body %>
       <%= f.text_area :body %>
    </p>
    <p><%= f.submit %>
    </p>
  <% end %>

app/views/posts/index.html.erb
<div class="row">
  <h4 align='center'>  we talk... </h4>
  <div class="col-md-2">


    quick <br />
    links



  </div>
    <div class="col-md-9">
<% @posts.each do |post| %>
  <div class='post_wrapper'>
    <h2 class='title'><%= link_to post.title, post %></h2>
    <p class='date'><%= post.created_at.strftime('%B, %d, %y') %></p>
  </div>
<% end %>
  </div>
  <div class="col-md-1">
social<br />
links
  </div>
</div>

app/views/posts/new.html.erb
<h1> New Post </h1>
  <%= form_for :post, url:posts_path do |f| %>
    <p><%= f.label :title %></br>
       <%= f.text_field :title %>
    </p>
    <p><%= f.label :body %>
       <%= f.text_area :body %>
    </p>
    <p><%= f.submit %>
    </p>
  <% end %>

app/views/posts/show.html.erb
<div class="row">
<div class="col-md-1">
quick<br />
links
</div>
<div class="col-md-10">
<h1 class='title' >
  <%= @post.title %>
</h1>

<p class='date'>
  submitted <%= time_ago_in_words (@post.created_at) %> ago
    <%= link_to 'edit', edit_post_path(@post) %>
    <%= button_to 'Delete', @post, method: :delete, data: {confirm: 'are you sure?'}%>
</p>

<p class='body'>
  <%= @post.body %>
</p>

<div id='comments'>
  <h2><%= @post.comments.count %> Comments </h2>
  <%= render @post.comments %>

  <h3>Add a comment</h3>
  <%= render "comments/form"%>
</div>
</div>
<div class="col-md-1">
share<br />
links
</div>
</div>

app/views/prices/edit.html.erb
<h1>Prices#edit</h1>
<%= form_for @price do |f| %>
<p><%= f.label :b_amount %></br>
   <%= f.text_field :b_amount %>
</p>
<p><%= f.label :name %></br>
   <%= f.text_field :name %>
</p>
<p><%= f.label :description %></br>
   <%= f.text_field :description %>
</p>
<p><%= f.label :indepth %></br>
   <%= f.text_field :indepth %>
</p>
<p><%= f.label :features %></br>
   <%= f.text_field :features %>
</p>
<p><%= f.submit %>
</p>
<% end %>
<%= button_to 'Delete', @price, method: :delete, data: {confirm: 'are you sure?'}%>

app/views/prices/index.html.erb
<div class="row">
  <h3 align='center'>Pricing list</h3>
  <div class="col-md-1">
    <div class="contain">
    <%= image_tag("rails.png", class: "img-responsive") %>
    <%= image_tag("reb.png", class: "img-responsive") %>
  </div>
  </div>
  <div class="col-md-10">
    <table class="table">
      <tr><th>Component_name</th><th>Component_use</th><th>price</th></tr>
  <% @prices.each do |price| %>
<tr><td><%= link_to price.name, price_path(price) %></td><td><%= link_to price.description, price_path(price) %></td><td><%= price.b_amount %>$</td></tr>
  <% end %>
    </table>
  </div>
  <div class="col-md-1">
<a href="https://www.facebook.com/elfonweb/"><i class="fa fa-facebook"></i></a> |<%= link_to contacts_new_path do %> <i class="fa fa-envelope"></i><% end %>
  </div>
</div>

app/views/prices/new.html.erb
<h1>Prices#new</h1>
<%= form_for @price do |f| %>
<p><%= f.label :b_amount %></br>
   <%= f.text_field :b_amount %>
</p>
<p><%= f.label :name %></br>
   <%= f.text_field :name %>
</p>
<p><%= f.label :description %></br>
   <%= f.text_field :description %>
</p>
<p><%= f.label :suggested_for %></br>
   <%= f.text_field :indepth %>
</p>
<p><%= f.label :features %></br>
   <%= f.text_field :features %>
</p>
<p><%= f.submit %>
</p>
<% end %>

app/views/prices/show.html.erb
<div class="row">
  <div class="col-md-1">
    <div class="contain">
    <%= image_tag("rails.png", class: "img-responsive") %>
    <%= image_tag("reb.png", class: "img-responsive") %>
  </div>
  </div>
  <div class="col-md-10">
<div class="price">
  <p class="bname"><%= @price.name %></p><br>
  <p class="bdescrp"><%= @price.description %></p><br>
<p class="bamount"><%= @price.b_amount %> $</p><br>
<p class="bamount">Suggested_for</p>
  <%= simple_format(@price.indepth) %>
<p class="bamount">Features</p>
  <%= simple_format(@price.features) %>
Please check <%= link_to demos_path do %>demo_page<% end %> for demo example (it is similar in pricing)
</div>
<div class="back">
<%= link_to 'Back', :back %>
</div>
</div>
<div class="col-md-1">
<a href="https://www.facebook.com/elfonweb/"><i class="fa fa-facebook"></i></a> |<%= link_to contacts_new_path do %> <i class="fa fa-envelope"></i><% end %>
</div>
</div>