config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'

resources "contacts", only: [:new, :create]
  resources :prices

  devise_for :users
  root 'home#index'


  resources :posts do
    resources :comments
  end


  resources :demos

  resources :projects

  get 'pages/our_thing'

  get 'pages/blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  append :remote_ip, :user_agent, :session

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "webelfs",
      :to => "compilitrate@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/demo.rb
class Demo < ApplicationRecord
  dragonfly_accessor :dpic
  dragonfly_accessor :mpic
  dragonfly_accessor :tpic
  dragonfly_accessor :r1pic
  dragonfly_accessor :r2pic
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  dragonfly_accessor :pic1
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :verify_is_admin, :only => [:new, :edit, :create, :destroy]
  def new
    @demo = Demo.new
  end

  def create
    @demo = Demo.new(demo_params)
    if @demo.save
      redirect_to @demo
    else
      render 'new'
    end
  end

  def index
    @demos = Demo.all.order('created_at DESC')
  end

  def show
    @demo = Demo.find(params[:id])
  end

  def edit
    @demo = Demo.find(params[:id])
  end

  def update
    @demo = Demo.find(params[:id])
    if @demo.update(params[:demo].permit(:d_pic, :m_pic, :t_pic, :r1_pic, :r2_pic, :name, :b_amount, :description))
      redirect_to demo_path
    else
      render 'edit'
    end
  end

  def destroy
    @demo = Demo.find(params[:id])
    @demo.destroy
    redirect_to demos_path
  end

  private

  def demo_params
    params.require(:demo).permit(:dpic, :mpic, :tpic, :r1pic, :r2pic, :name, :b_amount, :description)
  end

  def verify_is_admin
  (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def our_thing
  end
  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>webelfs</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script>
    $(function(){
        $('a').each(function(){
            if ($(this).prop('href') == window.location.href) {
                $(this).addClass('active'); $(this).parents('li').addClass('active');
            }
        });
    });
</script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="google-site-verification" content="c0PQ-UmCBIApYoC8amMrm-OFaT3laQ47ovn5VNG0cjs" />
<meta name="description"  content="Ready-made, hosted and maintained websites/webapps">
  </head>
<header>
  <div class="row">

      <div class="menu">
        <nav class="navbar navbar-custom " data-spy="affix" data-offset-top="50">
 <div class="container-fluid">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>

   </div>
   <div class="collapse navbar-collapse" id="myNavbar">
     <ul class="nav navbar-nav">
       <li><%=link_to 'Home', root_path %></li>
       <li><%=link_to 'Our_Wiki', pages_blog_path %></li>
       <li><%=link_to 'How_We_work', pages_our_thing_path %></li>
       <li><%=link_to 'Demos', demos_path %></li>
       <li><%=link_to 'Pricing', prices_path %></li>
       <li><%=link_to 'Contact_us', contacts_new_path  %></li>

     </ul>
     <ul class="nav navbar-nav navbar-right">
    <a class="navbar-brand" href="#">webelfs</a>
     </ul>
   </div>
 </div>
</nav>
</div>



  </div>
</header>
  <body>
  <main role="main">
<div class="container-fluid">

<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>
    <%= yield %>
</div>
  </main>
  </body>
</html>

app/views/pages/blog.html.erb
<div class="row">
  <h3 align="center">Wiki</h3>
  <div class="col-md-1">
  <div class="contain">
    <%= image_tag("rails.png", class: "img-responsive") %>
    <%= image_tag("reb.png", class: "img-responsive") %>
</div>
  </div>
  <div class="col-md-10">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

      <div class="panel panel-default">
        <div class="panel-heading panel-heading-custom" role="tab" id="headingFive">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                WebSite
            </a>
          </h4>
        </div>
        <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
          <div class="panel-body">
            <ul>
            <li>This is more of a ‘poster/billboard’ designed to get static information out there.</li>
            <li>Static means that this kind of information is not likely to change in the next; considerable time.</li>
            <li>Some websites are really advanced though.</li>
            <li>They allow you to set up a poster that can contact/subscribe to static information.</li>
            <li>We do that.</li>
          </ul>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading panel-heading-custom" role="tab" id="headingSeven">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                WebApp
            </a>
          </h4>
        </div>
        <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
          <div class="panel-body">
            <ul>
            <li>This is an interactive App(application); working/based on the Web.</li>
            <li>Interactive means that a user can actually do stuff like call, keep/create/edit records, shop, poke other social beings on the same App  and such like.</li>
            <li>The web part means that it’s interface is largely borrowed from website looks.</li>
            <li>Some are indistinguishable from websites.</li>
            <li>Others have different looks all simultaneously working from the same application; mobile, desktop and those in-betweens.</li>
            <li>We love doing those.</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading panel-heading-custom" role="tab" id="headingTwo">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Host/Hosting
            </a>
          </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="panel-body">
            <ul>
            <li>This is the facility running your project</li>
            <li>It like a big-brother version of your computer</li>
            <li>There for your clients and/or public</li>
            <li>It costs because; like your computer, it requires resources and skill to run</li>
            <li>Electricity, Internet-connectivity, (Storage,Processing), URL</li>
            <li>Skill</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading panel-heading-custom" role="tab" id="headingFour">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                URL
            </a>
          </h4>
        </div>
        <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
          <div class="panel-body">
            <ul>
            <li>Uniform Resourse Locator</li>
            <li>It is a human readable/rememberable name that connects to a very complex system of IP's to point it to your 'computer'; above</li>
            <li>IP(Internet Protocol) address generally in the form of ***.***.***.*** </li>
            <li>* ==> numeric (0-9)</li>
            <li>That's version four</li>
            <li>Version Six Exists</li>
            <li>Will tell you more once we find out what happened to version 5; if you do, contact_us </li>
            </ul>
          </div>
        </div>
      </div>


      </div>
  </div>
  <div class="col-md-1">
<a href="https://www.facebook.com/elfonweb/"><i class="fa fa-facebook"></i></a> |<%= link_to contacts_new_path do %> <i class="fa fa-envelope"></i><% end %>

  </div>
</div>

app/views/pages/our_thing.html.erb
<div class="row">
  <h3  align='center'>How_We_Work</h3>
  <div class="col-md-1">
  <div class="contain">
    <%= image_tag("rails.png", class: "img-responsive") %>
    <%= image_tag("reb.png", class: "img-responsive") %>
  </div>
  </div>

  <div class="col-md-10">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

<div class="panel panel-default">
  <div class="panel-heading panel-heading-custom" role="tab" id="headingFive">
    <h4 class="panel-title">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseYtr" aria-expanded="false" aria-controls="collapseYtr">
          1) Contact_us
      </a>
    </h4>
  </div>
  <div id="collapseYtr" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingYtr">
    <div class="panel-body">
      <ul><li>Let us know what you have in mind</li></ul>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-custom" role="tab" id="headingTwo">
    <h4 class="panel-title">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        2) Get notified on work start.
      </a>
    </h4>
  </div>
  <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
    <div class="panel-body">
      <ul>
        <li>You get an engineer/team fully responsible to your project</li>
        <li>Decide on how you will be communicating</li>
        <li>Let us know in case you do not like any part of this arrangement</li>
      </ul>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-custom" role="tab" id="headingThree">
    <h4 class="panel-title">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
         3) Decide on a design
      </a>
    </h4>
  </div>
  <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
    <div class="panel-body">
      <ul>
        <li>Get to modify and re-make </li>
        <li>Have complete freedom experessing your needs</li>
        <li>Ask for in house suggestions</li>
      </ul>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-custom" role="tab" id="headingFour">
    <h4 class="panel-title">
      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        4) We get down to work
      </a>
    </h4>
  </div>
  <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
    <div class="panel-body">
      <ul>
        <li>You will get looped on everything </li>
        <li>Slight modifications </li>
        <li>Aplha-testing</li>
      </ul>
      ...you will have a copy of the timeline: upon request (on select projects).
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-custom" role="tab" id="headingeleven">
    <h4 class="panel-title">
      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven" aria-expanded="true" aria-controls="collapseEleven">
        5)Beta-Testing
      </a>
    </h4>
  </div>
  <div id="collapseEleven" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingeleven">
    <div class="panel-body">
      <ul>
        <li>Get a staging site for your project</li>
        <li>Get minor changes effected</li>
        <li>Pay the agreed deposit(normaly 60%) </li>
      </ul>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading panel-heading-custom" role="tab" id="headingtwelve">
    <h4 class="panel-title">
      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwelve" aria-expanded="true" aria-controls="collapseTwelve">
        6)We Launch It
      </a>
    </h4>
  </div>
  <div id="collapseTwelve" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingtwelve">
    <div class="panel-body">
      <ul>
        <li>Complete the payment balance</li>
        <li>Get subscribed to our support mail for burst reports(monthly)</li>
        <li>Keep looking for ideas on making the project better </li>
      </ul>
    </div>
  </div>
</div>


</div>

  </div>
  <div class="col-md-1">
<a href="https://www.facebook.com/elfonweb/"><i class="fa fa-facebook"></i></a> |<%= link_to contacts_new_path do %> <i class="fa fa-envelope"></i><% end %>
  </div>
</div>